/**
 * Ícones exportados do Figma (Iconly + marcas) via `pnpm figma:icons`.
 * Monocromáticos usam `currentColor`; tamanho via className (ex.: `size-5`).
 */
export { default as SearchIcon } from '@/assets/icons/search.svg?react'
export { default as CartIcon } from '@/assets/icons/cart.svg?react'
export { default as LoginIcon } from '@/assets/icons/login.svg?react'
export { default as LogoutIcon } from '@/assets/icons/logout.svg?react'
export { default as FacebookIcon } from '@/assets/icons/facebook.svg?react'
export { default as InstagramIcon } from '@/assets/icons/instagram.svg?react'
export { default as TwitterIcon } from '@/assets/icons/twitter.svg?react'
export { default as LinkedinIcon } from '@/assets/icons/linkedin.svg?react'
export { default as YoutubeIcon } from '@/assets/icons/youtube.svg?react'
export { default as GoogleColorIcon } from '@/assets/icons/google-color.svg?react'
export { default as FacebookColorIcon } from '@/assets/icons/facebook-color.svg?react'
export { default as ThankYouIcon } from '@/assets/icons/thank-you.svg?react'
export { default as CloseIcon } from '@/assets/icons/close.svg?react'
export { default as HideIcon } from '@/assets/icons/hide.svg?react'
export { default as StarIcon } from '@/assets/icons/star.svg?react'
export { default as DeleteIcon } from '@/assets/icons/delete.svg?react'
export { default as ArrowLeftIcon } from '@/assets/icons/arrow-left.svg?react'
export { default as ArrowRightIcon } from '@/assets/icons/arrow-right.svg?react'
export { default as FilterIcon } from '@/assets/icons/filter.svg?react'
export { default as SearchMobileIcon } from '@/assets/icons/search-mobile.svg?react'
export { default as TabHomeIcon } from '@/assets/icons/tab-home.svg?react'
export { default as TabUserIcon } from '@/assets/icons/tab-user.svg?react'
export { default as TabShopIcon } from '@/assets/icons/tab-shop.svg?react'
export { default as TabHeartIcon } from '@/assets/icons/tab-heart.svg?react'
export { default as TabScanIcon } from '@/assets/icons/tab-scan.svg?react'
export { default as LocationIcon } from '@/assets/icons/location.svg?react'
export { default as ActivityIcon } from '@/assets/icons/activity.svg?react'
export { default as DownloadIcon } from '@/assets/icons/download.svg?react'
export { default as DangerIcon } from '@/assets/icons/danger.svg?react'
export { default as ImageIcon } from '@/assets/icons/image.svg?react'
export { default as ArrowDownIcon } from '@/assets/icons/arrow-down.svg?react'
export { default as WalletIcon } from '@/assets/icons/wallet.svg?react'
